//get ZONE data
export const GET_CITY_DATA = 'GET_CITY_DATA'
export const GET_CITY_DATA_REQUEST = 'GET_CITY_DATA_REQUEST'
export const GET_CITY_DATA_SUCCESS = 'GET_CITY_DATA_SUCCESS'
export const GET_CITY_DATA_FAILURE = 'GET_CITY_DATA_FAILURE'

//modal visiblity
export const GET_CITY_VISIBLE = 'GET_CITY_VISIBLE'
