//get customer data

export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA'
export const GET_CUSTOMER_DATA_REQUEST = 'GET_CUSTOMER_DATA_REQUEST'
export const GET_CUSTOMER_DATA_SUCCESS = 'GET_CUSTOMER_DATA_SUCCESS'
export const GET_CUSTOMER_DATA_FAILURE = 'GET_CUSTOMER_DATA_FAILURE'

//modal visiblity
export const GET_CUSTOMER_VISIBLE = 'GET_CUSTOMER_VISIBLE'

export const CUSTOMER_IMAGE_UPLOAD = 'CUSTOMER_IMAGE_UPLOAD'

export const ON_SUBMIT = 'ON_SUBMIT'
export const REMOVE_IMAGE = 'REMOVE_IMAGE'
