//get EquipmentHistory data
export const GET_EQUIPMENT_HISTORY_DATA = 'GET_EQUIPMENT_HISTORY_DATA'
export const GET_EQUIPMENT_HISTORY_DATA_REQUEST =
  'GET_EQUIPMENT_HISTORY_DATA_REQUEST'
export const GET_EQUIPMENT_HISTORY_DATA_SUCCESS =
  'GET_EQUIPMENT_HISTORY_DATA_SUCCESS'
export const GET_EQUIPMENT_HISTORY_DATA_FAILURE =
  'GET_EQUIPMENT_HISTORY_DATA_FAILURE'
