export const GET_EQUIPMENTS_DATA = 'GET_EQUIPMENTS_DATA'
export const GET_EQUIPMENTS_DATA_REQUEST = 'GET_EQUIPMENTS_DATA_REQUEST'
export const GET_EQUIPMENTS_DATA_SUCCESS = 'GET_EQUIPMENTS_DATA_SUCCESS'
export const GET_EQUIPMENTS_DATA_FAILURE = 'GET_EQUIPMENTS_DATA_FAILURE'

export const TOGGLE_EQUIPMENTS_HANDLE_MODAL = 'TOGGLE_EQUIPMENTS_HANDLE_MODAL'
export const SET_SELECTED_IMAGE_TO_UPLOAD = 'SET_SELECTED_IMAGE_TO_UPLOAD'
export const TOGGLE_ADD_ISSUES_MODAL = 'TOGGLE_ADD_ISSUES_MODAL'
export const SET_ADD_ISSUES_SELECTED_ROWS = 'SET_ADD_ISSUES_SELECTED_ROWS'
export const HANDLE_ISSUE_TITLE_CHANGE = 'HANDLE_ISSUE_TITLE_CHANGE'
export const TOGGLE_ADD_UPDATE_ISSUE_FORM = 'TOGGLE_ADD_UPDATE_ISSUE_FORM'

export const SET_SELECTED_ISSUE_EDITABLE = 'SET_SELECTED_ISSUE_EDITABLE'
export const CANCEL_ISSUE_EDITING = 'CANCEL_ISSUE_EDITING'
export const HANDLE_EDIT_ISSUE_CHANGE = 'HANDLE_EDIT_ISSUE_CHANGE'

export const TOGGLE_EQUIPMKENTS_MODAL_FOR_EDIT =
  'TOGGLE_EQUIPMKENTS_MODAL_FOR_EDIT'

export const GET_DEFAULT_ISSUES_LIST = 'GET_DEFAULT_ISSUES_LIST'
export const GET_DEFAULT_ISSUES_LIST_REQUEST = 'GET_DEFAULT_ISSUES_LIST_REQUEST'
export const GET_DEFAULT_ISSUES_LIST_SUCCESS = 'GET_DEFAULT_ISSUES_LIST_SUCCESS'
export const GET_DEFAULT_ISSUES_LIST_FAILURE = 'GET_DEFAULT_ISSUES_LIST_FAILURE'
export const HANDLE_REMOVE_FILE = 'HANDLE_REMOVE_FILE'

export const REMOVE_SELECTED_IMAGE_API = 'REMOVE_SELECTED_IMAGE_API'
export const REMOVE_SELECTED_IMAGE_API_REQUEST =
  'REMOVE_SELECTED_IMAGE_API_REQUEST'
export const REMOVE_SELECTED_IMAGE_API_SUCCESS =
  'REMOVE_SELECTED_IMAGE_API_SUCCESS'
export const REMOVE_SELECTED_IMAGE_API_FAILURE =
  'REMOVE_SELECTED_IMAGE_API_FAILURE'
