//get ZONE data
export const GET_ESCALATION_FLOW_DATA = 'GET_ESCALATION_FLOW_DATA'
export const GET_ESCALATION_FLOW_DATA_REQUEST =
  'GET_ESCALATION_FLOW_DATA_REQUEST'
export const GET_ESCALATION_FLOW_DATA_SUCCESS =
  'GET_ESCALATION_FLOW_DATA_SUCCESS'
export const GET_ESCALATION_FLOW_DATA_FAILURE =
  'GET_ESCALATION_FLOW_DATA_FAILURE'

//modal visiblity
export const GET_ESCALATION_FLOW_VISIBLE = 'GET_ESCALATION_FLOW_VISIBLE'
