//get ZONE data
export const GET_MODEL_DATA = 'GET_MODEL_DATA'
export const GET_MODEL_DATA_REQUEST = 'GET_MODEL_DATA_REQUEST'
export const GET_MODEL_DATA_SUCCESS = 'GET_MODEL_DATA_SUCCESS'
export const GET_MODEL_DATA_FAILURE = 'GET_MODEL_DATA_FAILURE'

//modal visiblity
export const GET_MODEL_VISIBLE = 'GET_MODEL_VISIBLE'
export const HANDLE_SELECT_EQUIPMENT_CHANGE = 'HANDLE_SELECT_EQUIPMENT_CHANGE'

export const HANDLE_SELECT_BRAND_CHANGE = 'HANDLE_SELECT_BRAND_CHANGE'
export const HANDLE_SELECT_MODEL_CHANGE = 'HANDLE_SELECT_MODEL_CHANGE'
