//get RELEASE_NOTE data
export const GET_RELEASE_NOTE_DATA = 'GET_RELEASE_NOTE_DATA'
export const GET_RELEASE_NOTE_DATA_REQUEST = 'GET_RELEASE_NOTE_DATA_REQUEST'
export const GET_RELEASE_NOTE_DATA_SUCCESS = 'GET_RELEASE_NOTE_DATA_SUCCESS'
export const GET_RELEASE_NOTE_DATA_FAILURE = 'GET_RELEASE_NOTE_DATA_FAILURE'
//modal visiblity
export const GET_RELEASE_NOTE_VISIBLE = 'GET_RELEASE_NOTE_VISIBLE'
//set description
export const SET_RELEASE_NOTE_DESCRIPTION = 'SET_RELEASE_NOTE_DESCRIPTION'

//VERSION NO
export const GET_VERSION_NO = 'GET_VERSION_NO'
