//get RELEASE APK data
export const GET_RELEASEAPK_DATA = 'GET_RELEASEAPK_DATA'
export const GET_RELEASEAPK_DATA_REQUEST = 'GET_RELEASEAPK_DATA_REQUEST'
export const GET_RELEASEAPK_DATA_SUCCESS = 'GET_RELEASEAPK_DATA_SUCCESS'
export const GET_RELEASEAPK_DATA_FAILURE = 'GET_RELEASEAPK_DATA_FAILURE'

//modal visiblity
export const GET_RELEASEAPK_VISIBLE = 'GET_RELEASEAPK_VISIBLE'

//upload apk file
export const UPLOAD_RELEASEAPK_FILE = 'UPLOAD_RELEASEAPK_FILE'

//reset apk form
export const RESET_APK_FORM = 'RESET_APK_FORM'

//disable upload
export const DISABLE_APK_UPLOAD = 'DISABLE_APK_UPLOAD'

export const SET_FILE_LIST = 'SET_FILE_LIST'
