//get report data
export const GET_REPORT_DATA = 'GET_REPORT_DATA'
export const GET_REPORT_DATA_REQUEST = 'GET_REPORT_DATA_REQUEST'
export const GET_REPORT_DATA_SUCCESS = 'GET_REPORT_DATA_SUCCESS'
export const GET_REPORT_DATA_FAILURE = 'GET_REPORT_DATA_FAILURE'

//modal visiblity
export const GET_REPORT_VISIBLE = 'GET_REPORT_VISIBLE'

export const ON_ZONE_CHANGE_ON_REPORT = 'ON_ZONE_CHANGE_ON_REPORT'
export const ON_CITY_CHANGE_ON_REPORT = 'ON_CITY_CHANGE_ON_REPORT'

//GET customer
export const GET_ALL_CUSTOMER_DATA = 'GET_ALL_CUSTOMER_DATA'
export const GET_ALL_CUSTOMER_DATA_REQUEST = 'GET_ALL_CUSTOMER_DATA_REQUEST'
export const GET_ALL_CUSTOMER_DATA_SUCCESS = 'GET_ALL_CUSTOMER_DATA_SUCCESS'
export const GET_ALL_CUSTOMER_DATA_FAILURE = 'GET_ALL_CUSTOMER_DATA_FAILURE'

// get ZONE
export const GET_ALL_ZONE_DATA = 'GET_ALL_ZONE_DATA'
export const GET_ALL_ZONE_DATA_REQUEST = 'GET_ALL_ZONE_DATA_REQUEST'
export const GET_ALL_ZONE_DATA_SUCCESS = 'GET_ALL_ZONE_DATA_SUCCESS'
export const GET_ALL_ZONE_DATA_FAILURE = 'GET_ALL_ZONE_DATA_FAILURE'

//get GET_ALL_STAFF_DATA

export const GET_ALL_STAFF_DATA = 'GET_ALL_STAFF_DATA'
export const GET_ALL_STAFF_DATA_REQUEST = 'GET_ALL_STAFF_DATA_REQUEST'
export const GET_ALL_STAFF_DATA_SUCCESS = 'GET_ALL_STAFF_DATA_SUCCESS'
export const GET_ALL_STAFF_DATA_FAILURE = 'GET_ALL_STAFF_DATA_FAILURE'

//GET CITY
export const GET_CITY_BY_ZONE_ID = 'GET_CITY_BY_ZONE_ID'
export const GET_CITY_BY_ZONE_ID_REQUEST = 'GET_CITY_BY_ZONE_ID_REQUEST'
export const GET_CITY_BY_ZONE_ID_SUCCESS = 'GET_CITY_BY_ZONE_ID_SUCCESS'
export const GET_CITY_BY_ZONE_ID_FAILURE = 'GET_CITY_BY_ZONE_ID_FAILURE'

//get location

export const GET_LOCATION_BY_ZONE_CITY_ID = 'GET_LOCATION_BY_ZONE_CITY_ID'
export const GET_LOCATION_BY_ZONE_CITY_ID_REQUEST =
  'GET_LOCATION_BY_ZONE_CITY_ID_REQUEST'
export const GET_LOCATION_BY_ZONE_CITY_ID_SUCCESS =
  'GET_LOCATION_BY_ZONE_CITY_ID_SUCCESS'
export const GET_LOCATION_BY_ZONE_CITY_ID_FAILURE =
  'GET_LOCATION_BY_ZONE_CITY_ID_FAILURE'
