//modal visiblity
export const GET_SERIALNO_VISIBLE = 'GET_SERIALNO_VISIBLE'

//serial data
export const GET_SERIAL_DATA = 'GET_SERIAL_DATA'
export const GET_SERIAL_DATA_REQUEST = 'GET_SERIAL_DATA_REQUEST'
export const GET_SERIAL_DATA_SUCCESS = 'GET_SERIAL_DATA_SUCCESS'
export const GET_SERIAL_DATA_FAILURE = 'GET_SERIAL_DATA_FAILURE'
export const ON_EQUIPMENT_CHANGE = 'ON_EQUIPMENT_CHANGE'
export const ON_BRAND_CHANGE = 'ON_BRAND_CHANGE'
export const ON_MODEL_CHANGE = 'ON_MODEL_CHANGE'
export const ON_ADD_SERIAL_NO = 'ON_ADD_SERIAL_NO'
export const ON_REMOVE_SERIAL_NO = 'ON_REMOVE_SERIAL_NO'
export const ON_CLEAR = 'ON_CLEAR'
