// Socket message,ticket recieved
export const SOCKET_MESSAGE_RECEIVED = 'SOCKET_MESSAGE_RECEIVED'
export const SOCKET_TICKET_RECEIVED = 'SOCKET_TICKET_RECEIVED'

// GET_CHAT_ROOMS
export const GET_CHAT_ROOMS = 'GET_CHAT_ROOMS'

// SELECTED_GROUP
export const SELECT_GROUP = 'SELECT_GROUP'

// GET_OUTLET_GROUP
export const GET_OUTLET_GROUP = 'GET_OUTLET_GROUP'
export const GET_OUTLET_GROUP_REQUEST = 'GET_OUTLET_GROUP_REQUEST'
export const GET_OUTLET_GROUP_SUCCESS = 'GET_OUTLET_GROUP_SUCCESS'
export const GET_OUTLET_GROUP_FAILURE = 'GET_OUTLET_GROUP_FAILURE'

// chat DATA
export const GET_CHAT_DATA = 'GET_CHAT_DATA'
export const GET_CHAT_DATA_REQUEST = 'GET_CHAT_DATA_REQUEST'
export const GET_CHAT_DATA_SUCCESS = 'GET_CHAT_DATA_SUCCESS'
export const GET_CHAT_DATA_FAILURE = 'GET_CHAT_DATA_FAILURE'

export const SELECT_CHAT_ROOM = 'SELECT_CHAT_ROOM'
export const CLEAR_COUNT = 'CLEAR_COUNT'
