//get staff list
export const GET_STAFF_LIST = 'GET_STAFF_LIST'
export const GET_STAFF_LIST_REQUEST = 'GET_STAFF_LIST_REQUEST'
export const GET_STAFF_LIST_SUCCESS = 'GET_STAFF_LIST_SUCCESS'
export const GET_STAFF_LIST_FAILURE = 'GET_STAFF_LIST_FAILURE'

//modal visiblity
export const GET_STAFF_VISIBLE = 'GET_STAFF_VISIBLE'

//staff information
export const SET_ROLE_TYPE = 'SET_ROLE_TYPE'
export const ACTIVE_STAFF_TAB = 'ACTIVE_STAFF_TAB'

//Selected Assign Outlet
export const ACTIVE_OUTLET_TAB = 'ACTIVE_OUTLET_TAB'

export const TOOGLE_VERIFY_INVITATION = 'TOOGLE_VERIFY_INVITATION'
export const ON_ADD_CITY_OUTLET = 'ON_ADD_CITY_OUTLET'
export const ON_REMOVE_CITY_OUTLET = 'ON_REMOVE_CITY_OUTLET'
export const ON_CHANGE_ZONE = 'ON_CHANGE_ZONE'
export const UPDATE_KEYS = 'UPDATE_KEYS'

//get selected cities
export const GET_SELECTED_CITIES = 'GET_SELECTED_CITIES'
export const GET_SELECTED_CITIES_REQUEST = 'GET_SELECTED_CITIES_REQUEST'
export const GET_SELECTED_CITIES_SUCCESS = 'GET_SELECTED_CITIES_SUCCESS'
export const GET_SELECTED_CITIES_FAILURE = 'GET_SELECTED_CITIES_FAILURE'

export const UPDATE_SELECTED_CITY_LIST_DATA = 'UPDATE_SELECTED_CITY_LIST_DATA'
export const UPDATE_CITY_LIST_DATA = 'UPDATE_CITY_LIST_DATA'
