//get store location data

export const GET_STORE_LOCATION_DATA = 'GET_STORE_LOCATION_DATA'
export const GET_STORE_LOCATION_DATA_REQUEST = 'GET_STORE_LOCATION_DATA_REQUEST'
export const GET_STORE_LOCATION_DATA_SUCCESS = 'GET_STORE_LOCATION_DATA_SUCCESS'
export const GET_STORE_LOCATION_DATA_FAILURE = 'GET_STORE_LOCATION_DATA_FAILURE'

// get LOCATION EQUIPMENT data

export const GET_LOCATION_EQUIPMENT_DATA = 'GET_LOCATION_EQUIPMENT_DATA'
export const GET_LOCATION_EQUIPMENT_DATA_REQUEST =
  'GET_LOCATION_EQUIPMENT_DATA_REQUEST'
export const GET_LOCATION_EQUIPMENT_DATA_SUCCESS =
  'GET_LOCATION_EQUIPMENT_DATA_SUCCESS'
export const GET_LOCATION_EQUIPMENT_DATA_FAILURE =
  'GET_LOCATION_EQUIPMENT_DATA_FAILURE'

// GET SATFF INFORMATION DATA

export const GET_SATFF_INFORMATION_DATA = 'GET_SATFF_INFORMATION_DATA'
export const GET_SATFF_INFORMATION_DATA_REQUEST =
  'GET_SATFF_INFORMATION_DATA_REQUEST'
export const GET_SATFF_INFORMATION_DATA_SUCCESS =
  'GET_SATFF_INFORMATION_DATA_SUCCESS'
export const GET_SATFF_INFORMATION_DATA_FAILURE =
  'GET_SATFF_INFORMATION_DATA_FAILURE'

// MODAL_VISIBLE

export const EQUIPMENT_MODAL_VISIBLE = 'EQUIPMENT_MODAL_VISIBLE'

export const EQUIPMENT_ADD_FORM = 'EQUIPMENT_ADD_FORM'
export const EQUIPMENT_CANCEL_FORM = 'EQUIPMENT_CANCEL_FORM'

export const EQUIPMENT_REMOVE_FORM_DATA = 'EQUIPMENT_REMOVE_FORM_DATA'

// edit equipment
export const SET_FILTER_BRAND_LIST_DATA = 'SET_FILTER_BRAND_LIST_DATA'
export const SET_FILTER_MODEL_LIST_DATA = 'SET_FILTER_MODEL_LIST_DATA'
export const ON_MODLE_CHANGE = 'ON_MODLE_CHANGE'
export const ON_SERIAL_NO_SELECT = 'ON_SERIAL_NO_SELECT'
export const ON_SERIAL_CHANGE = 'ON_SERIAL_NO_CHANGE'
export const ON_WARRANTY_CHANGE = 'ON_WARRANTY_CHANGE'
export const ON_INSTALLATION_DATE_CHANGE = 'ON_INSTALLATION_DATE_CHANGE'
export const ON_ZONE_CHANGE = 'ON_ZONE_CHANGE'

//get outets
export const GET_ALL_OUTLET_DATA_REQUEST = 'GET_ALL_OUTLET_DATA_REQUEST'
export const GET_ALL_OUTLET_DATA_SUCCESS = 'GET_ALL_OUTLET_DATA_SUCCESS'
export const GET_ALL_OUTLET_DATA_FAILURE = 'GET_ALL_OUTLET_DATA_FAILURE'
export const GET_ALL_OUTLET_DATA = 'GET_ALL_OUTLET_DATA'
export const UPDATE_SELECTED_OUTLET_LIST_DATA =
  'UPDATE_SELECTED_OUTLET_LIST_DATA'
