//get ZONE data
export const GET_TABLET_STATUS_DATA = 'GET_TABLET_STATUS_DATA'
export const GET_TABLET_STATUS_DATA_REQUEST = 'GET_TABLET_STATUS_DATA_REQUEST'
export const GET_TABLET_STATUS_DATA_SUCCESS = 'GET_TABLET_STATUS_DATA_SUCCESS'
export const GET_TABLET_STATUS_DATA_FAILURE = 'GET_TABLET_STATUS_DATA_FAILURE'

//modal visiblity
export const GET_TABLET_STATUS_VISIBLE = 'GET_TABLET_STATUS_VISIBLE'
