//
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'

// GET_SELECTED_WORK_ORDER_DATA
export const GET_SELECTED_WORK_ORDER_DATA = 'GET_SELECTED_WORK_ORDER_DATA'

export const GET_SELECTED_WORK_ORDER_DATA_REQUEST =
  'GET_SELECTED_WORK_ORDER_DATA_REQUEST'
export const GET_SELECTED_WORK_ORDER_DATA_SUCCESS =
  'GET_SELECTED_WORK_ORDER_DATA_SUCCESS'
export const GET_SELECTED_WORK_ORDER_DATA_FAILURE =
  'GET_SELECTED_WORK_ORDER_DATA_FAILURE'

//add Work order issue modal visiblity
export const GET_WORK_ORDER_VISIBLE = 'GET_WORK_ORDER_VISIBLE'

//get outlet data by customer
export const GET_OUTLET_DATA = 'GET_OUTLET_DATA'
export const GET_OUTLET_DATA_REQUEST = 'GET_OUTLET_DATA_REQUEST'
export const GET_OUTLET_DATA_SUCCESS = 'GET_OUTLET_DATA_SUCCESS'
export const GET_OUTLET_DATA_FAILURE = 'GET_OUTLET_DATA_FAILURE'

//get staff data by outlet
export const GET_STAFF_DATA = 'GET_STAFF_DATA'
export const GET_STAFF_DATA_REQUEST = 'GET_STAFF_DATA_REQUEST'
export const GET_STAFF_DATA_SUCCESS = 'GET_STAFF_DATA_SUCCESS'
export const GET_STAFF_DATA_FAILURE = 'GET_STAFF_DATA_FAILURE'

//get issues data by equipmet
export const GET_ISSUES_DATA = 'GET_ISSUES_DATA'
export const GET_ISSUES_DATA_REQUEST = 'GET_ISSUES_DATA_REQUEST'
export const GET_ISSUES_DATA_SUCCESS = 'GET_ISSUES_DATA_SUCCESS'
export const GET_ISSUES_DATA_FAILURE = 'GET_ISSUES_DATA_FAILURE'

//get equipments data by outlet
export const GET_EQUIPMENTS_DATA = 'GET_EQUIPMENTS_DATA'
export const GET_EQUIPMENTS_DATA_REQUEST = 'GET_EQUIPMENTS_DATA_REQUEST'
export const GET_EQUIPMENTS_DATA_SUCCESS = 'GET_EQUIPMENTS_DATA_SUCCESS'
export const GET_EQUIPMENTS_DATA_FAILURE = 'GET_EQUIPMENTS_DATA_FAILURE'

//get brands data by equipment
export const GET_BRANDS_DATA = 'GET_BRANDS_DATA'
export const GET_BRANDS_DATA_REQUEST = 'GET_BRANDS_DATA_REQUEST'
export const GET_BRANDS_DATA_SUCCESS = 'GET_BRANDS_DATA_SUCCESS'
export const GET_BRANDS_DATA_FAILURE = 'GET_BRANDS_DATA_FAILURE'

//get models data by brands
export const GET_MODELS_DATA = 'GET_MODELS_DATA'
export const GET_MODELS_DATA_REQUEST = 'GET_MODELS_DATA_REQUEST'
export const GET_MODELS_DATA_SUCCESS = 'GET_MODELS_DATA_SUCCESS'
export const GET_MODELS_DATA_FAILURE = 'GET_MODELS_DATA_FAILURE'

//get srnos data by models
export const GET_SRNOS_DATA = 'GET_SRNOS_DATA'
export const GET_SRNOS_DATA_REQUEST = 'GET_SRNOS_DATA_REQUEST'
export const GET_SRNOS_DATA_SUCCESS = 'GET_SRNOS_DATA_SUCCESS'
export const GET_SRNOS_DATA_FAILURE = 'GET_SRNOS_DATA_FAILURE'

//reset brands data
export const RESET_BRANDS_DATA = 'RESET_BRANDS_DATA'

//reset models data
export const RESET_MODELS_DATA = 'RESET_MODELS_DATA'

//reset srnos data
export const RESET_SRNOS_DATA = 'RESET_SRNOS_DATA'

//reset staff data
export const RESET_STAFF_DATA = 'RESET_STAFF_DATA'

//reset equipments data
export const RESET_EQUIPMENTS_DATA = 'RESET_EQUIPMENTS_DATA'

//image upload
export const WORK_ORDER_IMAGE_UPLOAD = 'WORK_ORDER_IMAGE_UPLOAD'
export const ON_SUBMIT = 'ON_SUBMIT'

//work order detail change data
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_TITLE_FIELDS = 'CHANGE_TITLE_FIELDS'

export const CHANGE_CUSTOMER = 'CHANGE_CUSTOMER'
export const CHANGE_CUSTOMER_FIELDS = 'CHANGE_CUSTOMER_FIELDS'

export const CHANGE_OUTLET = 'CHANGE_OUTLET'
export const CHANGE_OUTLET_FIELDS = 'CHANGE_OUTLET_FIELDS'

export const CHANGE_EQUIPMENT = 'CHANGE_EQUIPMENT'
export const CHANGE_EQUIPMENT_FIELDS = 'CHANGE_EQUIPMENT_FIELDS'

export const CHANGE_BRAND = 'CHANGE_BRAND'
export const CHANGE_BRAND_FIELDS = 'CHANGE_BRAND_FIELDS'

export const CHANGE_MODEL = 'CHANGE_MODEL'
export const CHANGE_MODEL_FIELDS = 'CHANGE_MODEL_FIELDS'

export const CHANGE_SRNOS = 'CHANGE_SRNOS'
export const CHANGE_SRNOS_FIELDS = 'CHANGE_SRNOS_FIELDS'

export const CHANGE_ASSIGNEE = 'CHANGE_ASSIGNEE'
export const CHANGE_ASSIGNEE_FIELDS = 'CHANGE_ASSIGNEE_FIELDS'

//WORK ORDER COMMENT
export const CHANGE_COMMENT_INPUT = 'CHANGE_COMMENT_INPUT'
export const SEND_COMMENT = 'SEND_COMMENT'
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS'
export const SEND_COMMENT_FAILURE = 'SEND_COMMENT_FAILURE'
export const SEND_COMMENT_REQUEST = 'SEND_COMMENT_REQUEST'

//visible manuals modal
export const GET_MANUALS_MODAL_VISIBLE = 'GET_MANUALS_MODAL_VISIBLE'

//visible report modal
export const GET_REPORT_MODAL_VISIBLE = 'GET_REPORT_MODAL_VISIBLE'

//report- service type checkbox
export const CHANGE_SERVICE_TYPE_CHECKBOX = 'CHANGE_SERVICE_TYPE_CHECKBOX'

//report - parts data
export const GET_PARTS_INPUT_VISIBLE = 'GET_PARTS_INPUT_VISIBLE'
export const CHANGE_PARTS_DATA = 'CHANGE_PARTS_DATA'
export const CHANGE_QTY = 'CHANGE_QTY'
export const CHANGE_PART_NO = 'CHANGE_PART_NO'
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION'

//REMOVE TICKET COUNT
export const REMOVE_TICKET_COUNT = 'REMOVE_TICKET_COUNT'

//get work order total count
export const GET_WORK_ORDER_UNREAD_COUNT = 'GET_WORK_ORDER_UNREAD_COUNT'

//update table pagination
export const GET_TABLE_PAGINATION = 'GET_TABLE_PAGINATION'

//WORK ORDER DATA WITH PAGINATION
export const GET_WORK_ORDER_DATA_PAGINATION = 'GET_WORK_ORDER_DATA_PAGINATION'
export const GET_WORK_ORDER_DATA_PAGINATION_REQUEST =
  'GET_WORK_ORDER_DATA_PAGINATION_REQUEST'
export const GET_WORK_ORDER_DATA_PAGINATION_SUCCESS =
  'GET_WORK_ORDER_DATA_PAGINATION_SUCCESS'
export const GET_WORK_ORDER_DATA_PAGINATION_FAILURE =
  'GET_WORK_ORDER_DATA_PAGINATION_FAILURE'

//change tab active key
export const CHANGE_TAB_ACTIVE_KEY = 'CHANGE_TAB_ACTIVE_KEY'

//disable upload button
export const DISABLE_UPLOAD = 'DISABLE_UPLOAD'
