//get ZONE data
export const GET_ZONE_DATA = 'GET_ZONE_DATA'
export const GET_ZONE_DATA_REQUEST = 'GET_ZONE_DATA_REQUEST'
export const GET_ZONE_DATA_SUCCESS = 'GET_ZONE_DATA_SUCCESS'
export const GET_ZONE_DATA_FAILURE = 'GET_ZONE_DATA_FAILURE'

//modal visiblity
export const GET_ZONE_VISIBLE = 'GET_ZONE_VISIBLE'

export const UPDATE_SELECTED_ZONE_DATA = 'UPDATE_SELECTED_ZONE_DATA'
